const productData = [
    {
        id: 0,
        img: "/Image/kitchenbeater.jpg",
        name: "Egg Beater",
        price: 550,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 1,
        img: "/Image/kitchenchopper.jpg",
        name: "Chopper",
        price: 1600 ,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 2,
        img: "/Image/kitchencuttingboard.jpg",
        name: "Cutting Board",
        price: 900 ,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 3,
        img: "/Image/kitchenjuicejar.jpg",
        name: "Juice Jar",
        price: 1600 ,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 4,
        img: "/Image/kitchenjuicer.jpg",
        name: "Juicer Machine",
        price: 1400 ,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 5,
        img: "/Image/kitchenoilbottle.jpg",
        name: "Oil Bottle",
        price: 1200 ,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 6,
        img: "/Image/kitchenspraybottle.jpg",
        name: "Oil Spray Bottle",
        price: 800 ,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 7,
        img: "/Image/kitchenwafflemaker.jpg",
        name: "Waffle Maker",
        price: 2200 ,
        category: ["KITCHEN UTENSILS"],
    },
    {
        id: 8,
        img: "/Image/kidsbag1.jpg",
        name: "School Bag",
        price: 2000 ,
        category: ["KIDS COLLECTION"],
    },
    {
        id: 9,
        img: "/Image/kidsbag2.jpg",
        name: "School Bag",
        price: 2000 ,
        category: ["KIDS COLLECTION"],
    },
    {
        id: 10,
        img: "/Image/kidsbag3.jpg",
        name: "School Bag",
        price: 2000 ,
        category: ["KIDS COLLECTION"],
    },
    {
        id: 11,
        img: "/Image/kidslunchbox.jpg",
        name: "Lunch Box",
        price: 1700 ,
        category: ["KIDS COLLECTION"],
    },
    {
        id: 12,
        img: "/Image/kidswaterbottle1.jpg",
        name: "Water Bottle",
        price: 1800 ,
        category: ["KIDS COLLECTION"],
    },
    {
        id: 13,
        img: "/Image/kidswaterbottle2.jpg",
        name: "Water Bottle",
        price: 1600 ,
        category: ["KIDS COLLECTION"],
    },
    
    {
        id: 14,
        img: "/Image/kidswaterbottle3.jpg",
        name: "Water Bottle",
        price: 2000 ,
        category: ["KIDS COLLECTION"],
    },
    {
        id: 15,
        img: "/Image/shopnowcamerabottle.jpeg",
        name: "Water Bottle",
        price: 2600 ,
        category: ["KIDS COLLECTION"],
    },
    {
        id: 16,
        img: "/Image/decormajicjar.jpg",
        name: "Majic Light Jar",
        price: 1200 ,
        category: ["HOME DECOR"],
    },
    {
        id: 17,
        img: "/Image/decorlamp1.jpg",
        name: "Lamp",
        price: 2200 ,
        category: ["HOME DECOR"],
    },
    {
        id: 18,
        img: "/Image/decorlamp2.jpg",
        name: "Lamp",
        price: 2000 ,
        category: ["HOME DECOR"],
    },
    {
        id: 19,
        img: "/Image/decorantiqueclock.jpg",
        name: "Antique Clock",
        price: 2200 ,
        category: ["HOME DECOR"],
    },
    {
        id: 20,
        img: "/Image/decorlightcandle.jpg",
        name: "Light Candle",
        price: 1200 ,
        category: ["HOME DECOR"],
    },
    {
        id: 21,
        img: "/Image/decorshowpiece.jpg",
        name: "Aladin Showpiece",
        price: 2600 ,
        category: ["HOME DECOR"],
    },
    
];

export default productData;
